### ISSUE TITLE
Align API with HTTPX changes

### ISSUE THREAD

**Issue by lundberg** [lundberg/respx#79]
HTTPX public API has seen some changes lately that should be addressed and aligned with in RESPX.

When adding patterns/responses, RESPX should support:
* [x] `params` (suggested in #63 and solved by #81)
* [ ] ~~`files` (investigate [POST fields](https://github.com/encode/httpx/pull/1032/files))~~ Moved #87 
* [ ] ~~`cookies` (investigate [format](https://github.com/encode/httpx/pull/1211))~~ Moved #87 
* [x] `text`, `html` and `json` (like existing *content -> json*, to mimic [Response](https://github.com/encode/httpx/blob/master/httpx/_models.py#L864). ~~Partly~~ Solved by #82 and #93)

**Comment by bowenwr** [comment]
Looking forward to this, as I currently have a conflict with a dependency that requires `httpx` 0.15.4.

**Comment by lundberg** [comment]
Current `respx` release supports `httpx` 0.15.4.

Did you mean something else, or have more detail on what `respx` could help solving your conflict @bowenwr ?

Feedback welcome!

**Comment by jairhenrique** [comment]
@lundberg can you release an version on pypi with supports `httpx` 0.15? 

```bash
poetry lock

Updating dependencies
Resolving dependencies... (0.3s)

[SolverProblemError]
Because respx (0.12.1) depends on httpx (>=0.14,<0.15)
 and no versions of respx match >0.12.1,<0.13.0, respx (>=0.12.1,<0.13.0) requires httpx (>=0.14,<0.15).
So, because ... depends on both httpx (^0.15.4) and respx (^0.12.1), version solving failed.
```

**Comment by mkuokkanen** [comment]
Hi, we are using respx 0.12.1 and poetry shows this to me

```
respx 0.12.1 A utility for mocking out the Python HTTPX and HTTP Core libraries.
└── httpx >=0.14,<0.15
```

Notice the upper limit <0.15. So having respx as dependency prevents us from upgrading to httpx 0.15.4. Looking forward for the latest changes. :)

**Comment by bowenwr** [comment]
@lundberg I'm having the exact problem @jairhenrique is having:

```
[SolverProblemError]
Because no versions of respx match >0.12.1,<0.13.0
 and respx (0.12.1) depends on httpx (>=0.14,<0.15), respx (>=0.12.1,<0.13.0) requires httpx (>=0.14,<0.15).
And because openapi-python-client (0.6.1) depends on httpx (^0.15.4)
 and no versions of openapi-python-client match !=0.6.1, respx (>=0.12.1,<0.13.0) is incompatible with openapi-python-client.
So, because openapi-specs depends on both openapi-python-client (*) and respx (^0.12.1), version solving failed.
```

**Comment by lundberg** [comment]
> @lundberg can you release an version on pypi with supports `httpx` 0.15?

Absolutely, released `0.13.0` now, sorry for the delay.

**Comment by lundberg** [comment]
> Notice the upper limit <0.15. So having respx as dependency prevents us from upgrading to httpx 0.15.4. Looking forward for the latest changes. :)

I removed the `HTTPX` upper limit in `0.13.0` @mkuokkanen . No need to have an upper limit, if it works with later HTTPX version then great, if not we still need to fix it ;-)

**Comment by bowenwr** [comment]
Thanks so much @lundberg, `0.13.0` solved my issue!

**Comment by mkuokkanen** [comment]
Super quick, thanks
