### ISSUE TITLE
Enhance request pattern matching

### ISSUE THREAD

**Issue by lundberg** [lundberg/respx#87]
To match and mock a request with certain content, *e.g. posted data*, a [request callback](https://lundberg.github.io/respx/api/#request-callback) is currently needed.

It would be nice to have an alternative way in the api, like http method and url, to allow request content matching, as discussed and proposed in #83. 

The HTTPX request API also supports `cookies` and `files`, which would be of interest to match on, as mentioned in #79.

* [x] `cookies` (investigate [format](https://github.com/encode/httpx/pull/1211)), Fixed by #99.
* [x] `content`, Fixed by #106 
* [x] `data`, Fixed by #106 
* [x] `json`, Fixed by #106 
* [ ] ~~`files` (investigate [POST fields](https://github.com/encode/httpx/pull/1032/files))~~ Moved to #115
